SET(DEFAULT_RUNSWIFT_CHECKOUT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/..")
IF (NOT IS_DIRECTORY "$ENV{RUNSWIFT_CHECKOUT_DIR}")
  IF (NOT IS_DIRECTORY "${DEFAULT_RUNSWIFT_CHECKOUT_DIR}/robot")
    MESSAGE(FATAL_ERROR "Please set the environment variable RUNSWIFT_CHECKOUT_DIR!")
  ELSE (NOT IS_DIRECTORY "${DEFAULT_RUNSWIFT_CHECKOUT_DIR}/robot")
    SET(RUNSWIFT_CHECKOUT_DIR "${DEFAULT_RUNSWIFT_CHECKOUT_DIR}")
  ENDIF (NOT IS_DIRECTORY "${DEFAULT_RUNSWIFT_CHECKOUT_DIR}/robot")
ELSE (NOT IS_DIRECTORY "$ENV{RUNSWIFT_CHECKOUT_DIR}")
  SET(RUNSWIFT_CHECKOUT_DIR "$ENV{RUNSWIFT_CHECKOUT_DIR}")
ENDIF (NOT IS_DIRECTORY "$ENV{RUNSWIFT_CHECKOUT_DIR}")

SET(RUNSWIFT_ROBOT_DIR "${RUNSWIFT_CHECKOUT_DIR}/robot")

INCLUDE_DIRECTORIES(${RUNSWIFT_ROBOT_DIR})
